- example/SampleApp/sampleApp/App.tsx
- example/SampleApp/sampleApp/index.js
- example/SampleApp/sampleApp/package.json
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/context/postLikesListContext.tsx
- likeminds-feed-reactnative-integration/context/postListContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
- likeminds-feed-reactnative-integration/customModals/DeleteReasonsModal/index.tsx
- likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
- likeminds-feed-reactnative-integration/index.ts
- likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
- likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
- likeminds-feed-reactnative-integration/utils/AWSConfig.ts
- likeminds-feed-reactnative-integration/utils/uploadFilesToAWS.ts
- likeminds-feed-reactnative-ui/package.json
**Features**
**Bugs**
1. versions are very high -> 0.73.2 is used, it should down graded to minimum supported
2. All the dependencies are not in peer_dependency
3. ContextProvider  should be inside LMFeedProvider
> [LM-10898] Fixed demo changes

- example/SampleApp/sampleApp/index.js
- example/SampleApp/sampleApp/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- likeminds-feed-reactnative-integration/tsconfig.json
- likeminds-feed-reactnative-integration/utils/uploadFilesToAWS.ts
**Features**
1. Changed versions
**Bugs**
> Version Changes for v0.7.0

- example/SampleApp/sampleApp/App.tsx
- example/SampleApp/sampleApp/feedScreen/feed.tsx
- likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedCallbacksContext.tsx
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
**Features**
1. share post functionality added
**Bugs**
> [LM-10435] Added share post

- example/SampleApp/sampleApp/feedScreen/feed.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/types.ts
- likeminds-feed-reactnative-integration/components/LMPost/LMPostMedia/index.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/context/postListContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
**Features**
- Added video auto play/pause feature
**Bugs**
> [LM-10996] Video auto play/pause functionality

- likeminds-feed-reactnative-integration/components/LMMedia/LMScrollDocument/index.tsx
- likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
- likeminds-feed-reactnative-integration/screens/createPost/index.tsx
- likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
> [LM-11116] Peer Testing R2

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
-  version change
**Bugs**
> [v1.0.0] - Version Upgrade

- likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
- likeminds-feed-reactnative-integration/components/LMCommentItem/types.ts
- likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
- likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
- likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
**Features**
**Bugs**
- Sometimes text field comes below the keyboard in the post details screen
- if the opened same post is from 2 diff devices → add comment from one device → go to post details screen on second device → add comment from second device→ then comment count is not same as feed screen and post details screen
- on adding a reply to comment it should be visible below comment, it is visible when there is no comments , but if i close the reply section and then reply to that post then it stayed in collapsed state
> [LM-11119] Resolved release v1 blockers

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Version upgrade
> [v1.0.1] Version Upgrade

- example/App.tsx
- example/index.js
- example/login/credentials.ts
- example/login/index.tsx
- example/login/loginSchemaRO.ts
- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Api key switcher
**Bugs**
> Release v1.0.1

- example/package.json
- likeminds-feed-reactnative-integration/package.json
**Features**
- Poll in feed
**Bugs**
> [v1.2.0] Version Upgrade

- example/App.tsx
- example/styles.ts
- likeminds-feed-reactnative-integration/callBacks/carouselScreenCallbacks.tsx
- likeminds-feed-reactnative-integration/components/LMPoll/CreatePollUI/index.tsx
- likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
- likeminds-feed-reactnative-integration/components/LMPost/LMPostPollText/index.tsx
- likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/index.ts
- likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
- likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
- likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
- likeminds-feed-reactnative-integration/screens/carouselScreen/index.tsx
**Features**
- Added customisations
- Added aspect ratio checks while selecting image
**Bugs**
> [LM-11192] Aspect ratio and Customisations

- example/package.json
- likeminds-feed-reactnative-integration/package.json
**Features**
- Upgradede version
**Bugs**
> [Release-v1.3.0] Upgraded versions

- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/screens/createPost/index.tsx
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/viewDataModels/index.ts
**Features**
**Bugs**
- Bug bash bugs
> Bug Bash Issues

- likeminds-feed-reactnative-integration/components/LMMedia/LMImage/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMImage/types.ts
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/types.ts
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
**Features**
- Added height and aspectRatio support
**Bugs**
> [LM-11193] Aspect Ratio Padding

- example/package.json
- likeminds-feed-reactnative-integration/package.json
**Features**
- Upgraded version
**Bugs**
> Upgraded versions

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Upgraded version
**Bugs**
> [v1.7.0] Version Upgrade

- example/App.tsx
- likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
- likeminds-feed-reactnative-integration/customModals/LMPostMenu/index.tsx
- likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
- likeminds-feed-reactnative-integration/models/LMCommentUI.ts
- likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
- likeminds-feed-reactnative-integration/store/reducers/postDetailReducer.ts
- likeminds-feed-reactnative-integration/utils/commentResponseModelConvertor.ts
- likeminds-feed-reactnative-integration/viewDataModels/index.ts
**Features**
- Bug fixes  for comments and replies for a post
**Bugs**
- Overflow menu not appearing for replies
- Editing a reply not working
> [LM-12608] Replies Overflow Menu

- example/App.tsx
- example/android/build.gradle
- example/package.json
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/package.json
**Features**
- Migration: Target SDK 34
> [LM-12226] Migration: Target SDK 34

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Version Upgrade
**Bugs**
> [v.1.8.0] Version Upgrade

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Version upgrade
> [v.1.8.1] Version Upgrade

- example/package.json
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Version Upgrade
> [v.1.8.2] Version Upgrade

- likeminds-feed-reactnative-integration/.npmignore
- likeminds-feed-reactnative-integration/package.json
**Features**
jenkins pipeline test
**Bugs**
> added .npmignore file and increased beta version

- likeminds-feed-reactnative-integration/.npmignore
- likeminds-feed-reactnative-integration/Jenkinsfile
**Features**
- Jenkinsfile and .npmignore files added. 
**Bugs**
> [LM-12652] Builds Jenkins Pipeline 

- .github/workflows/create-tag-and-release.yml
- example/package.json
- likeminds-feed-reactnative-integration/.npmignore
- likeminds-feed-reactnative-integration/Jenkinsfile
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
**Features**
- Added Jenkinsfile and .npmignore file
- Added workflow dispatch for triggering action remotely.
**Bugs**
> Release v1.8.3

- likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollView/index.tsx
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/context/notificationFeedContext.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/context/postLikesListContext.tsx
- likeminds-feed-reactnative-integration/context/postListContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
- likeminds-feed-reactnative-integration/customModals/DeleteReasonsModal/index.tsx
- likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
- likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
> Request Builder Fix

- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
- Version upgrade
> [v1.9.0] Version Upgrade

- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/types.ts
- likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
- likeminds-feed-reactnative-integration/index.ts
- likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
- likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
- likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
- likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
- likeminds-feed-reactnative-integration/optionalDependencies/Video.ts
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- likeminds-feed-reactnative-integration/setupFeed.ts
- social-feed/App.tsx
- social-feed/package.json
**Features**
- Video as Optional dependency & Callback Support
**Bugs**
> Video as Optional dependency & Callback Support

- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/context/notificationFeedContext.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/context/postItemContext.tsx
- likeminds-feed-reactnative-integration/context/postLikesListContext.tsx
- likeminds-feed-reactnative-integration/context/postListContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
- likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
**Features**
- Childern types issue
> [Hotfix] Children types issue

- likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
- likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/styles.ts
- likeminds-feed-reactnative-integration/context/userOnboardingContext.tsx
- likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
- likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
- likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
- likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/topicFeed/index.tsx
- likeminds-feed-reactnative-integration/screens/topicFeed/styles.ts
- likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
- likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
- likeminds-feed-reactnative-integration/uiComponents/LMInputText/utils.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
- Post footer UI fixed.
**Bugs**
> [LM-13119] Feed Bugs

- likeminds-feed-reactnative-integration/package.json
**Features**
**Bugs**
- Build issues fixed due to TS version.
> [HOTFIX] TS Version

- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostUserTagging.tsx
- likeminds-feed-reactnative-integration/components/LMCreatePost/LMUserProfileSection.tsx
- likeminds-feed-reactnative-integration/components/LMMemberListItem/index.tsx
- likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/index.tsx
- likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/LMFeedCreatePollScreen/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- likeminds-feed-reactnative-integration/uiComponents/LMProfilePicture/types.ts
- qna-feed/package.json
- social-feed/package.json
**Bugs**
- Profile picture styling customisations
> [LM-13186] Profile Picture Styling Customisations

- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostAttachmentSelection.tsx
- likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
- likeminds-feed-reactnative-integration/context/postListContext.tsx
- likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- likeminds-feed-reactnative-integration/wrappers/qnaFeedScreenWrapper.tsx
- likeminds-feed-reactnative-integration/wrappers/socialFeedScreenWrapper.tsx
- qna-feed/package.json
- social-feed/package.json
**Features**
**Bugs**
- Selected topics
- Hide attachments options
> [Hotfix] Selected Topics & Hide Attachments options

- likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/carouselScreen/styles.ts
- likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- likeminds-feed-reactnative-integration/store/store.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
**Bugs**
- Reset store action
- Made deviceId optional in Logout method
- Added background color of status bar on userOnBoarding screen according to theme.
- Back arrow on carousel screen is visible properly.
> [Hotfix] Reset Store Actions & Styles

- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
**Bugs**
- React Native version check removed at RN layer.
> [Hotfix] Gradle Build Issue

- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Bugs**
- Data type issue in getTopics() method
> [LM-13428] Data Type issue

- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostAttachmentSelection.tsx
- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostTextInput.tsx
- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostUIRender.tsx
- likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostUserTagging.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMImage/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
- likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/styles.ts
- likeminds-feed-reactnative-integration/context/createPostContext.tsx
- likeminds-feed-reactnative-integration/screens/carouselScreen/index.tsx
- likeminds-feed-reactnative-integration/screens/createPost/styles.ts
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/uiComponents/LMInputText/index.tsx
- likeminds-feed-reactnative-integration/wrappers/socialFeedCreateWrapper.tsx
**Features**
- Fixed UI issues in create post screen and carousel.
**Bugs**
> [LM-11481] Feed Bugs

- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/searchFeed/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
- Search In Feed.
- Retry Mechanism.
**Bugs**
- UI issues fixed.
> Release/v1.13.0-PSO 

- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
**Bugs**
- Topic Categorization Fix.
> [Hotfix] Search Param Fix

- likeminds-feed-reactnative-integration/components/LMPost/LMPostText/index.tsx
- likeminds-feed-reactnative-integration/context/postDetailContext.tsx
- likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
- likeminds-feed-reactnative-integration/screens/postsList/index.tsx
- likeminds-feed-reactnative-integration/screens/searchFeed/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
**Bugs**
- Modal not opening for React Native versions >=0.76.
> [Hotfix] Modal Issue Fix iOS

- likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
- likeminds-feed-reactnative-integration/package.json
- likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
- likeminds-feed-reactnative-integration/setup.ts
- qna-feed/package.json
- social-feed/package.json
**Features**
- User Onboarding Flow updated.
**Bugs**
> [LM-13598] User Onboarding Fix

- .github/workflows/branch-check.yml
**Features**
- added branch-check yml filw
**Bugs**
> chore: added branch-check yml filw
